name: 'weather'
version: '1.0'

profile: 'weather'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

models:
  weather:
      base:
          materialized: ephemeral
      dimensions:
          materialized: table
      reports:
          materialized: table
      meta:
          tags: "expensive"
          materialized: table
          schema: meta
