version: 2

models:
  - name: denormalized_temp_data
    description: A table containing denormalized temp hi/low and location
    tests:
      - unique:
          column_name: "concat(station_id, date)"


    columns:
    - name: min_celsius
      description: minum temp in degrees celsius

    - name: max_celsius
      description: maximum temp in degrees celsius

    - name: station_id
      description: weather station identifier
      tests:
        - not_null

    - name: latitude
      description: location of recording
      tests:
        - not_null

    - name: longitude
      description: location of recording
      tests:
        - not_null

    - name: date
      description: recording date
      tests:
        - not_null

